export enum SearchColumns {
  Status = 'Status',
  LastModifiedBy = 'Modified By',
  NameRequestNumber = 'NR Number',
  Names = 'Names',
  ApplicantFirstName = 'Applicant First Name',
  ApplicantLastName = 'Applicant Last Name',
  NatureOfBusiness = 'Nature Of Business',
  ConsentRequired = 'Consent Required',
  Priority = 'Priority',
  ClientNotification = 'Notified',
  Submitted = 'Submitted',
  LastUpdate = 'Last Update',
  LastComment = 'Last Comment',
}
