name: NAME-EXAMINATION UI CI

on:
  pull_request:
    types: [assigned, synchronize]
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  nameexamination-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/frontend-ci.yaml@main
    with:
      app_name: "nameexamination"
      working_directory: "./app"
      codecov_flag: ""
